# Generated by Django 5.2.7 on 2025-11-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('formula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Particula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_electrica', models.CharField(max_length=100)),
                ('tamanio', models.CharField(max_length=100)),
            ],
        ),
    ]
