# Generated by Django 5.2.7 on 2025-11-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='formula',
            field=models.CharField(),
        ),
    ]
