# Generated by Django 5.2.7 on 2025-11-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_energia_formula'),
    ]

    operations = [
    ]
