# Generated by Django 5.2.7 on 2025-11-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20251107_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='particula',
            old_name='tamanio',
            new_name='nombre',
        ),
    ]
